// ⚙️ Auto-generated by tools/update_version.dart
// Do not edit manually.

const String appVersion = '1.1.0';
const String buildTime = '2026-01-25 15:00:59';

const String whatsNew = '''
📦 Version 1.0.6 Updates:
- ✨ Stunning New Dashboard: Added animated StatCards with tiered gradients and hover effects.
- 🛡️ Auto-Error Logger: Implemented global error interception with silent email reporting.
- 📧 Mailer Upgrade: Updated to mailer 6.0.1 for more robust SMTP performance.
- 📍 Release Refinements: Hidden debug banners and technical notifications for a cleaner experience.
- 🧹 Performance: General bug fixes and UI performance optimizations.
''';
